/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "GPIO.h"
#include "FreeRTOS.h"
#include "task.h"

void LED_Blink(void*);

uint32_t SystemCoreClock = 180000000;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(uint32_t counter)
{
	for(uint32_t i=0; i<counter*1000; i++);
}

uint8_t volatile u8_LocPushed = 0u;

int main(void)
{
	int8_t LocRet=0;

	/******* Initializing FPU in CPACR *******/
	uint32_t* CPACR_ptr = (uint32_t*)0xE000ED88;						//Address of CPACR register
	*CPACR_ptr |= ((3UL << 10*2) | (3UL << 11*2));						//Set coprocessor 10 and 11 to b11

	/* Init */
	GPIO_StructInit_t LED_Toggle = {
			13u,
			GPIO_ePinMode_Output,
			GPIO_eOutType_PushPull,
			GPIO_ePuPdMode_NoPuPd,
			GPIO_ePinOSpeed_VeryHigh,
			0u
	};

	GPIO_ClockControl(GPIO_eCLKPOS_C, ENABLE);
	GPIO_Init(GPIOC, &LED_Toggle);

	GPIO_StructInit_t Push_Button = {
			0u,
			GPIO_ePinMode_Input,
			GPIO_eOutType_PushPull,
			GPIO_ePuPdMode_PullUp,
			GPIO_ePinOSpeed_VeryHigh,
			0u
	};

	GPIO_ClockControl(GPIO_eCLKPOS_A, ENABLE);
	GPIO_Init(GPIOA, &Push_Button);

	/* Create FreeRTOS Task */
	LocRet = xTaskCreate(&LED_Blink, "BlinkTask", 250u, 0, 0, NULL);

    /* Start FreeRTOS Scheduler */
	vTaskStartScheduler();
}

void LED_Blink(void* arg)
{
	for(;;)
	{
		if(GPIO_ReadPin(GPIOA,0U))
		{
			delay(20);								//Debounce

			GPIO_WritePin(GPIOC,13u,HIGH);			//LED off
		}
		else
		{
			delay(20);								//Debounce

			for(uint32_t i=0; i<50; i++)			//LED Low intensity on (similar to PWM)
			{
				GPIO_WritePin(GPIOC,13u,HIGH);
				delay(20);
				GPIO_WritePin(GPIOC,13u,LOW);
				delay(1);
			}

			GPIO_WritePin(GPIOC,13u,HIGH);			//LED off
			delay(500);
		}
	}
}
